{% set name = "cantera_adaptive_testing" %}
{% set packname = "cantera_adaptive_testing" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: "https://github.com/anthony-walker/cantera-adaptive-testing"

build:
  number: 0
  entry_points:
    - 'adaptive-testing=cantera_adaptive_testing.commandline:cmd_line_main'
  script: "{{ PYTHON }} -m pip install . -vv"
requirements:
  host:
    - cantera
    - mpi4py
    - matplotlib
    - pip
    - python
  run:
    - cantera
    - matplotlib
    - mpi4py
    - python
test:
  imports:
    - cantera_adaptive_testing
  commands:
    - pyplume.figures --help
    - pyplume.statistics --help
    - pyplume.model --help
    - pyplume.mech --help

about:
  home: "https://github.com/anthony-walker/cantera-adaptive-testing"
  license: MIT
  license_family: MIT
  summary: "This package contains files to test new functionality in cantera."
  doc_url: "https://pypi.org/project/pyplume/"
  dev_url: "https://github.com/anthony-walker/cantera-adaptive-testing"
  description: "This package is used for testing preconditioner additions to Cantera and running studies on the additions."
extra:
  recipe-maintainers:
    - anthony-walker
